/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class graphics_MotorGrafico */

#ifndef _Included_graphics_MotorGrafico
#define _Included_graphics_MotorGrafico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     graphics_MotorGrafico
 * Method:    init
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_graphics_MotorGrafico_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     graphics_MotorGrafico
 * Method:    update
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_graphics_MotorGrafico_update
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     graphics_MotorGrafico
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_graphics_MotorGrafico_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
